apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        name: postgres
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: PGDATA
              value: /pg-data
          image: localhost:5001/postgres:17.5
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /pg-data
              name: data-volume
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "postgres" -d "postgres"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-pg-data


