apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 5432
      protocol: TCP
  selector:
    app: postgres
