apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
    name: keycloak-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-server
  template:
    metadata:
      labels:
        app: keycloak-server
        name: keycloak-server
    spec:
      containers:
      - name: keycloak-server
        image: localhost:5001/keycloak/keycloak:22.0.5
        env:
          - name: KC_PROXY
            value: "edge"
          - name: KC_HOSTNAME_URL
            value: https://keycloak.localtest.me
          - name: KC_HOSTNAME_ADMIN_URL
            value: https://keycloak.localtest.me
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KEYCLOAK_ADMIN
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
          - name: KC_DB
            value: "postgres"
          - name: KC_DB_URL
            value: "jdbc:postgresql://postgres-service.default.svc.cluster.local:5432/keycloak"
          - name: KC_DB_USERNAME
            value: "postgres"
          - name: KC_DB_PASSWORD
            value: "postgres"
          - name: TZ
            value: "Europe/Copenhagen"
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start"
          - "--https-certificate-file=/run/secrets/tls/tls.crt"
          - "--https-certificate-key-file=/run/secrets/tls/tls.key"
        ports:
          - containerPort: 8080
            name: http
          - containerPort: 8443
            name: https
        volumeMounts:
          - mountPath: /run/secrets/tls
            name: cert
      volumes:
        - name: cert
          secret:
            secretName: keycloak-tls
