apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
            - name: RABBITMQ_PLUGINS
              value: rabbitmq_delayed_message_exchange rabbitmq_management
          image: 'localhost:5001/bitnami/rabbitmq:4.0.5'
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          volumeMounts:
            - mountPath: >-
                /opt/bitnami/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.9.0.ez
              name: plugins
              subPath: rabbitmq_delayed_message_exchange-3.9.0.ez
          ports:
            - containerPort: 4369
              protocol: TCP
            - containerPort: 5671
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15671
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
            - containerPort: 25672
              protocol: TCP
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: rabbitmq-plugins
          name: plugins
