apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-server
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 6379
      nodePort: 30971
      name: redis
      protocol: TCP
  selector:
    app: redis-server
