apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmCharts:
  - repo: https://dl.gitea.com/charts
    name: gitea
    version: 10.1.0
    releaseName: gitea
    valuesFile: manifests/values.yaml

resources:
  - manifests/gitea-localtest-me.yaml
  - manifests/gitea-data-storage.yaml
