apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.17.0
  http:
    tls:
      certificate:
        secretName: easykube-ca
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
#  http:
#    tls:
#      certificate:
#        secretName: default-cert