apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  http:
    tls:
      certificate:
        secretName: easykube-ca
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.publicBaseUrl: "https://kibana.localtest.me"