---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitea-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 300M
  hostPath:
    path: /storage/gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea-data
spec:
  storageClassName: standard
  volumeName: pv-gitea-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M